# Generated by Django 4.0.4 on 2022-07-15 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres del director', max_length=40)),
                ('apellidos', models.CharField(help_text='Apellidos del director', max_length=40)),
                ('edad', models.CharField(help_text='Edad del director', max_length=3)),
                ('correo', models.CharField(help_text='Correo del director', max_length=40)),
                ('genre', models.CharField(help_text='Genero del director', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Genero de pelicula', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la pelicula', max_length=30)),
                ('sinopsis', models.TextField(help_text='Resumen de la pelicula', max_length=100)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.director')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Restriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Tipo de restriccion', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID de la pelicula', primary_key=True, serialize=False)),
                ('fecha_estreno', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('m', 'Muy pronto'), ('c', 'En cartelera')], default='m', help_text='Estado de pelicula', max_length=1)),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='restriccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.restriccion'),
        ),
    ]
